#mysql 配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/back_app?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#jpa 配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#thymeleaf 配置
  thymeleaf:
    cache: false